display tmux window id in message if available
franciscolourenco/done pull request #115
Opened 2021-09-18 18:13 UTC by Azenet

2021-09-29 10:35 UTC, franciscolourenco commented
@Azenet can you share an example of what this looks like in practice? Thanks!

2021-09-29 11:18 UTC, Azenet commented
@franciscolourenco It adds `[@2]` at the beginning of the notification if the process was running in window 2, for example.

2021-10-01 11:27 UTC, Azenet commented
I was using the wrong variable for the display, which became apparent after using tmux for a long time in which windows were closed (id stays unique). Also added a configuration variable for the format, defaults to `[2]` for window 2 for example.

2023-09-26 23:59 UTC, franciscolourenco requested changes
Can you share a screenshot showing what the notification looks like?

2023-09-26 23:59 UTC, franciscolourenco commented on conf.d/done.fish
> +		set message (tmux lsw  -F"$__done_tmux_pane_format" -f '#{==:#{pane_id},'$TMUX_PANE'}')" $message"
I like the PR, could you please just indent this line?

2023-09-27 01:03 UTC, Azenet commented
Sure, here is what the notification looks like after `sleep 10` has ended in pane 30: 
![Screenshot_20230927_025859](https://github.com/franciscolourenco/done/assets/770806/a50a33e0-9a0c-4e07-a3da-f44cad3f88af)

Rebased and made the requested change.

2023-09-27 14:43 UTC, franciscolourenco commented
Thank you @Azenet! This will be released in v1.17.0.

2023-09-27 14:43 UTC, merged